name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test:coverage

      - name: Build package
        run: pnpm build

      - name: Debug build folder
        run: |
          ls -a ./build
        # uses: actions/github-script@0.5.0
        # with:
        #   script: |
        #     console.log(
        #       "package.json",
        #       require("fs").readFileSync(
        #         "./build/package.json",
        #         "utf8",
        #       ),
        #     );
      - name: Publish npm package
        uses: cycjimmy/semantic-release-action@v3
        env:
          GH_TOKEN: ${{ secrets.CI_SEMANTIC_RELEASE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
